spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.7:3306/mandofin_test?characterEncoding=utf-8&useSSL=false
        username: mando_root
        password: dev@110
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 200 #最大连接数
        initialSize: 1 #初始化连接
        maxWait: 60000 #连接超时时间
        minIdle: 1     #最小连接数
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000 #最大空闲时间
     #   validationQuery: select 'x'  不用该配置性能较高
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ya.song.entity.User

server:
  port: 8081
ys:
  name: yinyasong







